spring:
  application:
    name: oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    url: jdbc:mysql://localhost:3306/auth3?useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://192.168.18.30:3306/auth3?useUnicode=true&characterEncoding=utf8
    username: ecuser
    password: qazwsx
#    username: sa
#    password: password
  sql:
    init:
      mode: always      
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console.enabled: true      
       
server:
  port: ${port:5566}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name:  /logs/auth-dev.log
  level:
    org.springframework: info
    com.example.demo: debug

security:
  oauth2:
    authorization:
      jwt:
        key-value: '我難過的是放棄你放棄愛放棄的夢被打碎忍住悲哀'
